name: Run CI checks

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Building affected apps
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: bahmutov/npm-install@v1
      - run: npm run nx affected -- --target=build --base=origin/main --parallel=3
      - run: npm run nx affected -- --target=test --base=origin/main --parallel=3
      - run: npm run nx affected -- --target=lint --base=origin/main --parallel=3
      - run: npm run nx affected -- --target=e2e --base=origin/main --parallel=1
